### PR TITLE
Update to Kodi Nexus

### PR DESCRIPTION
**Pull request by daanvandevliet**

### CODE REVIEW

**Comment by daanvandevliet** [comment]
Credits go to @SmellyCat69 and @fugkco

**Comment by fugkco** [comment]
@daanvandevliet thanks for the PR. I'm just trying to set up, so I can test it before I review and merge. I'm kind of curious how you got elementum working on Nexus, as it doesn't seem to want to install due to kodi_six not being installed, which in turn cannot be installed as it's for older versions of Kodi.

**Comment by daanvandevliet** [comment]
@fugkco thanks for going through the trouble. I just tested a clean install of Kodi Nexus and elementum installed as expected. I installed the universal package from the official website.

I hope that helps!

**Review by fugkco — APPROVED** [review]

**Comment by fugkco** [comment]
I'll make a release soon.

**Pull request merged**
